services:
  - type: web
    name: elow-backend
    env: node
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5005
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
